version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"

  - package-ecosystem: "nuget"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
