services:
  database:
    container_name: "kijk-db"
    image: "postgres:alpine"
    restart: "on-failure"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kijk
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  data-volume:
