/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedWelcomeImport } from './routes/_protected/welcome'
import { Route as ProtectedHomeImport } from './routes/_protected/home'
import { Route as ProtectedHomeIndexImport } from './routes/_protected/home/index'
import { Route as ProtectedHomeBudgetRouteImport } from './routes/_protected/home/budget/route'
import { Route as ProtectedHomeSettingsIndexImport } from './routes/_protected/home/settings/index'
import { Route as ProtectedHomeSettingsSectionIndexImport } from './routes/_protected/home/settings/$section/index'

// Create Virtual Routes

const ProtectedHomeBudgetBudgetPendingLazyImport = createFileRoute(
  '/_protected/home/budget/budget-pending',
)()
const ProtectedHomeBudgetBudgetErrorLazyImport = createFileRoute(
  '/_protected/home/budget/budget-error',
)()
const ProtectedHomeBudgetBudgetLazyImport = createFileRoute(
  '/_protected/home/budget/budget',
)()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedWelcomeRoute = ProtectedWelcomeImport.update({
  path: '/welcome',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedHomeRoute = ProtectedHomeImport.update({
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedHomeIndexRoute = ProtectedHomeIndexImport.update({
  path: '/',
  getParentRoute: () => ProtectedHomeRoute,
} as any)

const ProtectedHomeBudgetRouteRoute = ProtectedHomeBudgetRouteImport.update({
  path: '/budget',
  getParentRoute: () => ProtectedHomeRoute,
} as any)

const ProtectedHomeSettingsIndexRoute = ProtectedHomeSettingsIndexImport.update(
  {
    path: '/settings/',
    getParentRoute: () => ProtectedHomeRoute,
  } as any,
)

const ProtectedHomeBudgetBudgetPendingLazyRoute =
  ProtectedHomeBudgetBudgetPendingLazyImport.update({
    path: '/budget-pending',
    getParentRoute: () => ProtectedHomeBudgetRouteRoute,
  } as any).lazy(() =>
    import('./routes/_protected/home/budget/budget-pending.lazy').then(
      (d) => d.Route,
    ),
  )

const ProtectedHomeBudgetBudgetErrorLazyRoute =
  ProtectedHomeBudgetBudgetErrorLazyImport.update({
    path: '/budget-error',
    getParentRoute: () => ProtectedHomeBudgetRouteRoute,
  } as any).lazy(() =>
    import('./routes/_protected/home/budget/budget-error.lazy').then(
      (d) => d.Route,
    ),
  )

const ProtectedHomeBudgetBudgetLazyRoute =
  ProtectedHomeBudgetBudgetLazyImport.update({
    path: '/budget',
    getParentRoute: () => ProtectedHomeBudgetRouteRoute,
  } as any).lazy(() =>
    import('./routes/_protected/home/budget/budget.lazy').then((d) => d.Route),
  )

const ProtectedHomeSettingsSectionIndexRoute =
  ProtectedHomeSettingsSectionIndexImport.update({
    path: '/settings/$section/',
    getParentRoute: () => ProtectedHomeRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_protected/home': {
      preLoaderRoute: typeof ProtectedHomeImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/welcome': {
      preLoaderRoute: typeof ProtectedWelcomeImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/home/budget': {
      preLoaderRoute: typeof ProtectedHomeBudgetRouteImport
      parentRoute: typeof ProtectedHomeImport
    }
    '/_protected/home/': {
      preLoaderRoute: typeof ProtectedHomeIndexImport
      parentRoute: typeof ProtectedHomeImport
    }
    '/_protected/home/budget/budget': {
      preLoaderRoute: typeof ProtectedHomeBudgetBudgetLazyImport
      parentRoute: typeof ProtectedHomeBudgetRouteImport
    }
    '/_protected/home/budget/budget-error': {
      preLoaderRoute: typeof ProtectedHomeBudgetBudgetErrorLazyImport
      parentRoute: typeof ProtectedHomeBudgetRouteImport
    }
    '/_protected/home/budget/budget-pending': {
      preLoaderRoute: typeof ProtectedHomeBudgetBudgetPendingLazyImport
      parentRoute: typeof ProtectedHomeBudgetRouteImport
    }
    '/_protected/home/settings/': {
      preLoaderRoute: typeof ProtectedHomeSettingsIndexImport
      parentRoute: typeof ProtectedHomeImport
    }
    '/_protected/home/settings/$section/': {
      preLoaderRoute: typeof ProtectedHomeSettingsSectionIndexImport
      parentRoute: typeof ProtectedHomeImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProtectedRoute.addChildren([
    ProtectedHomeRoute.addChildren([
      ProtectedHomeBudgetRouteRoute.addChildren([
        ProtectedHomeBudgetBudgetLazyRoute,
        ProtectedHomeBudgetBudgetErrorLazyRoute,
        ProtectedHomeBudgetBudgetPendingLazyRoute,
      ]),
      ProtectedHomeIndexRoute,
      ProtectedHomeSettingsIndexRoute,
      ProtectedHomeSettingsSectionIndexRoute,
    ]),
    ProtectedWelcomeRoute,
  ]),
  AuthRoute,
])

/* prettier-ignore-end */
