/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SsoCallbackImport } from './routes/sso-callback'
import { Route as AuthImport } from './routes/auth'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedWelcomeImport } from './routes/_protected/welcome'
import { Route as ProtectedSettingsImport } from './routes/_protected/settings'
import { Route as ProtectedHomeImport } from './routes/_protected/home'
import { Route as ProtectedBudgetImport } from './routes/_protected/budget'
import { Route as ProtectedSettingsSectionImport } from './routes/_protected/settings.$section'

// Create/Update Routes

const SsoCallbackRoute = SsoCallbackImport.update({
  path: '/sso-callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedWelcomeRoute = ProtectedWelcomeImport.update({
  path: '/welcome',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedSettingsRoute = ProtectedSettingsImport.update({
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedHomeRoute = ProtectedHomeImport.update({
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedBudgetRoute = ProtectedBudgetImport.update({
  path: '/budget',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedSettingsSectionRoute = ProtectedSettingsSectionImport.update({
  path: '/$section',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_protected/budget': {
      id: '/_protected/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof ProtectedBudgetImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/welcome': {
      id: '/_protected/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof ProtectedWelcomeImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/settings/$section': {
      id: '/_protected/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof ProtectedSettingsSectionImport
      parentRoute: typeof ProtectedSettingsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  ProtectedRoute: ProtectedRoute.addChildren({
    ProtectedBudgetRoute,
    ProtectedHomeRoute,
    ProtectedSettingsRoute: ProtectedSettingsRoute.addChildren({
      ProtectedSettingsSectionRoute,
    }),
    ProtectedWelcomeRoute,
    ProtectedIndexRoute,
  }),
  AuthRoute,
  SsoCallbackRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/auth",
        "/sso-callback"
      ]
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/budget",
        "/_protected/home",
        "/_protected/settings",
        "/_protected/welcome",
        "/_protected/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/sso-callback": {
      "filePath": "sso-callback.tsx"
    },
    "/_protected/budget": {
      "filePath": "_protected/budget.tsx",
      "parent": "/_protected"
    },
    "/_protected/home": {
      "filePath": "_protected/home.tsx",
      "parent": "/_protected"
    },
    "/_protected/settings": {
      "filePath": "_protected/settings.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/settings/$section"
      ]
    },
    "/_protected/welcome": {
      "filePath": "_protected/welcome.tsx",
      "parent": "/_protected"
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/settings/$section": {
      "filePath": "_protected/settings.$section.tsx",
      "parent": "/_protected/settings"
    }
  }
}
ROUTE_MANIFEST_END */
