// <auto-generated />
using System;
using Kijk.Infrastructure.Persistence;
using Kijk.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kijk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001190802_HouseholdRolesAndPermissions")]
    partial class HouseholdRolesAndPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "creator_type", new[] { "system", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kijk.Domain.Entities.Consumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CalculatedConsumption")
                        .HasColumnType("numeric")
                        .HasColumnName("calculated_consumption");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<bool>("StartsNewMeterSegment")
                        .HasColumnType("boolean")
                        .HasColumnName("starts_new_meter_segment");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_consumptions");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_consumptions_household_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_consumptions_name");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_consumptions_resource_id");

                    b.ToTable("consumptions", (string)null);
                });

            modelBuilder.Entity("Kijk.Domain.Entities.ConsumptionLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime?>("LastOccurrence")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_occurrence");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_consumptions_limits");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_consumptions_limits_created_by_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_consumptions_limits_name");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_consumptions_limits_resource_id");

                    b.HasIndex("HouseholdId", "ResourceId", "Period")
                        .IsUnique()
                        .HasDatabaseName("ix_consumptions_limits_household_id_resource_id_period");

                    b.ToTable("consumptions_limits", (string)null);
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_households_name");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51af63b7-f581-48a5-8987-937939b56dec"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "consumptions:view"
                        },
                        new
                        {
                            Id = new Guid("80abd19c-7609-40a6-a296-d4310d3771f0"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "consumptions:record"
                        },
                        new
                        {
                            Id = new Guid("4c18ae0c-f592-4398-8226-b89f6150c314"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "consumptions:export"
                        },
                        new
                        {
                            Id = new Guid("6a994db4-6fce-4538-bb38-1c8a2edca792"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "limits:view"
                        },
                        new
                        {
                            Id = new Guid("5ca7bb07-cf8b-4930-8047-e4c857c4fc65"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "limits:plan"
                        },
                        new
                        {
                            Id = new Guid("c2d383b8-545f-43d1-b5bb-44a2f184934a"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "resources:view"
                        },
                        new
                        {
                            Id = new Guid("af500b09-178e-4fd2-8e20-387b84c91fac"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "resources:configure"
                        },
                        new
                        {
                            Id = new Guid("57820fa1-c443-458d-b8d3-40ef527720d4"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "units:share"
                        },
                        new
                        {
                            Id = new Guid("0e065002-1522-4138-a96b-52e657b7cbcc"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "household:configure"
                        },
                        new
                        {
                            Id = new Guid("4ab7acac-5b5f-41b4-a3f7-7174694781b1"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "household:delete"
                        },
                        new
                        {
                            Id = new Guid("55d9913b-dcb6-43bc-b9b8-0b840508c795"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "members:view"
                        },
                        new
                        {
                            Id = new Guid("39e9c646-8685-4fb5-a0d9-68233d3d605c"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "members:assign-role"
                        });
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#89CEA4")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<CreatorType>("CreatorType")
                        .HasColumnType("creator_type")
                        .HasColumnName("creator_type");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("circle")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("normalized_name")
                        .HasComputedColumnSql("lower(btrim(name))", true);

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_resources_name");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_resources_unit_id");

                    b.HasIndex("NormalizedName", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_resources_normalized_name_unit_id")
                        .HasFilter("household_id IS NULL");

                    b.HasIndex("HouseholdId", "NormalizedName", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_resources_household_id_normalized_name_unit_id")
                        .HasFilter("household_id IS NOT NULL");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("0195624d-3c82-73e8-bb7b-b3fac043f2cb"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Member"
                        },
                        new
                        {
                            Id = new Guid("3e42fa02-77ac-4bb9-a9a8-d031a3b8ea75"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<decimal?>("ConversionFactor")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("conversion_factor");

                    b.Property<string>("ConversionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("conversion_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<CreatorType>("CreatorType")
                        .HasColumnType("creator_type")
                        .HasColumnName("creator_type");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_name")
                        .HasComputedColumnSql("lower(btrim(name))", true);

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("QuantityKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quantity_key");

                    b.Property<Guid?>("ReferenceUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_unit_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("UnitsNetUnitName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("units_net_unit_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("ReferenceUnitId")
                        .HasDatabaseName("ix_units_reference_unit_id");

                    b.HasIndex("OwnerUserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_units_owner_user_id_normalized_name")
                        .HasFilter("creator_type = 'user' AND archived_at IS NULL");

                    b.HasIndex("QuantityKey", "UnitsNetUnitName")
                        .IsUnique()
                        .HasDatabaseName("ix_units_quantity_key_units_net_unit_name")
                        .HasFilter("creator_type = 'system'");

                    b.ToTable("units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Liter",
                            QuantityKey = "Volume",
                            Symbol = "l",
                            UnitsNetUnitName = "Liter"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111112"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Milliliter",
                            QuantityKey = "Volume",
                            Symbol = "ml",
                            UnitsNetUnitName = "Milliliter"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111113"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Cubic meter",
                            QuantityKey = "Volume",
                            Symbol = "m³",
                            UnitsNetUnitName = "CubicMeter"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222221"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Watt hour",
                            QuantityKey = "Energy",
                            Symbol = "Wh",
                            UnitsNetUnitName = "WattHour"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Kilowatt hour",
                            QuantityKey = "Energy",
                            Symbol = "kWh",
                            UnitsNetUnitName = "KilowattHour"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222223"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Megawatt hour",
                            QuantityKey = "Energy",
                            Symbol = "MWh",
                            UnitsNetUnitName = "MegawattHour"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333331"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Gram",
                            QuantityKey = "Mass",
                            Symbol = "g",
                            UnitsNetUnitName = "Gram"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333332"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Kilogram",
                            QuantityKey = "Mass",
                            Symbol = "kg",
                            UnitsNetUnitName = "Kilogram"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333333"),
                            ConversionType = "UnitsNet",
                            CreatedAt = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorType = CreatorType.System,
                            Name = "Tonne",
                            QuantityKey = "Mass",
                            Symbol = "t",
                            UnitsNetUnitName = "Tonne"
                        });
                });

            modelBuilder.Entity("Kijk.Domain.Entities.UnitHousehold", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shared_at");

                    b.Property<Guid>("SharedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("shared_by_user_id");

                    b.HasKey("UnitId", "HouseholdId")
                        .HasName("pk_unit_households");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_unit_households_household_id");

                    b.HasIndex("SharedByUserId")
                        .HasDatabaseName("ix_unit_households_shared_by_user_id");

                    b.ToTable("unit_households", (string)null);
                });

            modelBuilder.Entity("Kijk.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AnalyticsConsent")
                        .HasColumnType("integer")
                        .HasColumnName("analytics_consent");

                    b.Property<DateTime?>("AnalyticsConsentUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analytics_consent_updated_at");

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auth_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarding_completed_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AuthId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kijk.Domain.Entities.UserHousehold", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "HouseholdId")
                        .HasName("pk_user_households");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_user_households_household_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_user_households_is_active");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_households_role_id");

                    b.ToTable("user_households", (string)null);
                });

            modelBuilder.Entity("roles_permissions", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid")
                        .HasColumnName("permissions_id");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid")
                        .HasColumnName("roles_id");

                    b.HasKey("PermissionsId", "RolesId")
                        .HasName("pk_roles_permissions");

                    b.HasIndex("RolesId")
                        .HasDatabaseName("ix_roles_permissions_roles_id");

                    b.ToTable("roles_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionsId = new Guid("51af63b7-f581-48a5-8987-937939b56dec"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("80abd19c-7609-40a6-a296-d4310d3771f0"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("4c18ae0c-f592-4398-8226-b89f6150c314"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("6a994db4-6fce-4538-bb38-1c8a2edca792"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("5ca7bb07-cf8b-4930-8047-e4c857c4fc65"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("c2d383b8-545f-43d1-b5bb-44a2f184934a"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("af500b09-178e-4fd2-8e20-387b84c91fac"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("57820fa1-c443-458d-b8d3-40ef527720d4"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("0e065002-1522-4138-a96b-52e657b7cbcc"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("4ab7acac-5b5f-41b4-a3f7-7174694781b1"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("55d9913b-dcb6-43bc-b9b8-0b840508c795"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("39e9c646-8685-4fb5-a0d9-68233d3d605c"),
                            RolesId = new Guid("0195624d-5bd9-754c-a92b-5e0e82e1ede1")
                        },
                        new
                        {
                            PermissionsId = new Guid("51af63b7-f581-48a5-8987-937939b56dec"),
                            RolesId = new Guid("0195624d-3c82-73e8-bb7b-b3fac043f2cb")
                        },
                        new
                        {
                            PermissionsId = new Guid("80abd19c-7609-40a6-a296-d4310d3771f0"),
                            RolesId = new Guid("0195624d-3c82-73e8-bb7b-b3fac043f2cb")
                        },
                        new
                        {
                            PermissionsId = new Guid("4c18ae0c-f592-4398-8226-b89f6150c314"),
                            RolesId = new Guid("0195624d-3c82-73e8-bb7b-b3fac043f2cb")
                        },
                        new
                        {
                            PermissionsId = new Guid("6a994db4-6fce-4538-bb38-1c8a2edca792"),
                            RolesId = new Guid("0195624d-3c82-73e8-bb7b-b3fac043f2cb")
                        },
                        new
                        {
                            PermissionsId = new Guid("c2d383b8-545f-43d1-b5bb-44a2f184934a"),
                            RolesId = new Guid("0195624d-3c82-73e8-bb7b-b3fac043f2cb")
                        },
                        new
                        {
                            PermissionsId = new Guid("55d9913b-dcb6-43bc-b9b8-0b840508c795"),
                            RolesId = new Guid("0195624d-3c82-73e8-bb7b-b3fac043f2cb")
                        },
                        new
                        {
                            PermissionsId = new Guid("51af63b7-f581-48a5-8987-937939b56dec"),
                            RolesId = new Guid("3e42fa02-77ac-4bb9-a9a8-d031a3b8ea75")
                        },
                        new
                        {
                            PermissionsId = new Guid("6a994db4-6fce-4538-bb38-1c8a2edca792"),
                            RolesId = new Guid("3e42fa02-77ac-4bb9-a9a8-d031a3b8ea75")
                        },
                        new
                        {
                            PermissionsId = new Guid("c2d383b8-545f-43d1-b5bb-44a2f184934a"),
                            RolesId = new Guid("3e42fa02-77ac-4bb9-a9a8-d031a3b8ea75")
                        },
                        new
                        {
                            PermissionsId = new Guid("55d9913b-dcb6-43bc-b9b8-0b840508c795"),
                            RolesId = new Guid("3e42fa02-77ac-4bb9-a9a8-d031a3b8ea75")
                        });
                });

            modelBuilder.Entity("users_resources", b =>
                {
                    b.Property<Guid>("ResourcesId")
                        .HasColumnType("uuid")
                        .HasColumnName("resources_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ResourcesId", "UserId")
                        .HasName("pk_users_resources");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_users_resources_user_id");

                    b.ToTable("users_resources", (string)null);
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Consumption", b =>
                {
                    b.HasOne("Kijk.Domain.Entities.Household", "Household")
                        .WithMany("Consumptions")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumptions_households_household_id");

                    b.HasOne("Kijk.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumptions_resources_resource_id");

                    b.Navigation("Household");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.ConsumptionLimit", b =>
                {
                    b.HasOne("Kijk.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumptions_limits_users_created_by_id");

                    b.HasOne("Kijk.Domain.Entities.Household", "Household")
                        .WithMany("ConsumptionLimits")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumptions_limits_households_household_id");

                    b.HasOne("Kijk.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumptions_limits_resources_resource_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Household");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Resource", b =>
                {
                    b.HasOne("Kijk.Domain.Entities.Household", "Household")
                        .WithMany("Resources")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_resources_households_household_id");

                    b.HasOne("Kijk.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_units_unit_id");

                    b.Navigation("Household");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Unit", b =>
                {
                    b.HasOne("Kijk.Domain.Entities.User", "OwnerUser")
                        .WithMany("Units")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_units_users_owner_user_id");

                    b.HasOne("Kijk.Domain.Entities.Unit", "ReferenceUnit")
                        .WithMany()
                        .HasForeignKey("ReferenceUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_units_units_reference_unit_id");

                    b.Navigation("OwnerUser");

                    b.Navigation("ReferenceUnit");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.UnitHousehold", b =>
                {
                    b.HasOne("Kijk.Domain.Entities.Household", "Household")
                        .WithMany("UnitHouseholds")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_households_households_household_id");

                    b.HasOne("Kijk.Domain.Entities.User", "SharedByUser")
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_unit_households_users_shared_by_user_id");

                    b.HasOne("Kijk.Domain.Entities.Unit", "Unit")
                        .WithMany("Households")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_households_units_unit_id");

                    b.Navigation("Household");

                    b.Navigation("SharedByUser");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.UserHousehold", b =>
                {
                    b.HasOne("Kijk.Domain.Entities.Household", "Household")
                        .WithMany("UserHouseholds")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_households_households_household_id");

                    b.HasOne("Kijk.Domain.Entities.Role", "Role")
                        .WithMany("UserHouseholds")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_households_roles_role_id");

                    b.HasOne("Kijk.Domain.Entities.User", "User")
                        .WithMany("UserHouseholds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_households_users_user_id");

                    b.Navigation("Household");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("roles_permissions", b =>
                {
                    b.HasOne("Kijk.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permissions_permissions_permissions_id");

                    b.HasOne("Kijk.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permissions_roles_roles_id");
                });

            modelBuilder.Entity("users_resources", b =>
                {
                    b.HasOne("Kijk.Domain.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_resources_resources_resources_id");

                    b.HasOne("Kijk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_resources_users_user_id");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Household", b =>
                {
                    b.Navigation("ConsumptionLimits");

                    b.Navigation("Consumptions");

                    b.Navigation("Resources");

                    b.Navigation("UnitHouseholds");

                    b.Navigation("UserHouseholds");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserHouseholds");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Households");
                });

            modelBuilder.Entity("Kijk.Domain.Entities.User", b =>
                {
                    b.Navigation("Units");

                    b.Navigation("UserHouseholds");
                });
#pragma warning restore 612, 618
        }
    }
}
