<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Kijk.ArchitectureTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET.TUnit" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Api/Api.csproj" />
    <ProjectReference Include="../../src/Application/Application.csproj" />
    <ProjectReference Include="../../src/Domain/Domain.csproj" />
    <ProjectReference Include="../../src/Infrastructure/Infrastructure.csproj" />
    <ProjectReference Include="../../src/Shared/Shared.csproj" />
  </ItemGroup>
</Project>
