import { defineConfig } from "oxlint";

/**
 * OxLint configuration for JSDoc rules.
 */
export default defineConfig({
  plugins: ["jsdoc"],
  rules: {
    "jsdoc/check-access": "warn",
    "jsdoc/check-alignment": "warn",
    "jsdoc/check-examples": "off",
    "jsdoc/check-indentation": "off",
    "jsdoc/check-line-alignment": "off",
    "jsdoc/check-param-names": "warn",
    "jsdoc/check-property-names": "warn",
    "jsdoc/check-synonyms": "off",
    "jsdoc/check-tag-names": "warn",
    "jsdoc/check-types": "warn",
    "jsdoc/closing-template": "off",
    "jsdoc/empty-tags": "warn",
    "jsdoc/implements-on-classes": "warn",
    "jsdoc/match-name": "off",
    "jsdoc/newline-after-description": "warn",
    "jsdoc/no-bad-blocks": "warn",
    "jsdoc/no-defaults": "off",
    "jsdoc/no-duplicate-class-tags": "warn",
    "jsdoc/no-missing-syntax": "off",
    "jsdoc/no-multi-assign": "off",
    "jsdoc/no-restricted-syntax": "off",
    "jsdoc/no-undefined-types": "warn",
    "jsdoc/require-asterisk-prefix": "off",
    "jsdoc/require-description": "off",
    "jsdoc/require-description-complete-sentence": "off",
    "jsdoc/require-example": "off",
    "jsdoc/require-hyphen-before-param-description": "off",
    "jsdoc/require-jsdoc": "off",
    "jsdoc/require-param": "warn",
    "jsdoc/require-param-description": "warn",
    "jsdoc/require-param-name": "warn",
    "jsdoc/require-returns": "warn",
    "jsdoc/require-returns-check": "warn",
    "jsdoc/require-returns-description": "warn",
    "jsdoc/require-throws": "warn",
    "jsdoc/require-yields": "warn",
    "jsdoc/require-yields-check": "warn",
    "jsdoc/sort-tags": "off",
    "jsdoc/tag-lines": "off",
    "jsdoc/toolchain": "off",
    "jsdoc/update-copyright": "off",
    "jsdoc/valid-types": "warn",
  },
});
