export const reactHooksJsPlugin = {
  name: 'react-hooks-js',
  specifier: 'eslint-plugin-react-hooks',
} as const;

export const reactHooksRules = {
  'react-hooks-js/component-hook-factories': 'error',
  'react-hooks-js/config': 'error',
  'react-hooks-js/error-boundaries': 'error',
  'react-hooks-js/gating': 'error',
  'react-hooks-js/globals': 'error',
  'react-hooks-js/immutability': 'error',
  'react-hooks-js/incompatible-library': 'error',
  'react-hooks-js/preserve-manual-memoization': 'error',
  'react-hooks-js/purity': 'error',
  'react-hooks-js/refs': 'error',
  'react-hooks-js/set-state-in-effect': 'warn',
  'react-hooks-js/set-state-in-render': 'error',
  'react-hooks-js/static-components': 'error',
  'react-hooks-js/unsupported-syntax': 'error',
  'react-hooks-js/use-memo': 'error',
  'react-hooks-js/void-use-memo': 'error',
  'react-hooks-js/automatic-effect-dependencies': 'off',
  'react-hooks-js/capitalized-calls': 'off',
  'react-hooks-js/fbt': 'off',
  'react-hooks-js/fire': 'off',
  'react-hooks-js/hooks': 'off',
  'react-hooks-js/invariant': 'off',
  'react-hooks-js/memoized-effect-dependencies': 'off',
  'react-hooks-js/no-deriving-state-in-effects': 'off',
  'react-hooks-js/rule-suppression': 'off',
  'react-hooks-js/syntax': 'off',
  'react-hooks-js/todo': 'off',
} as const;
