using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Kijk.Api.SourceGenerators;

/// <summary>
/// Generates compile-time dependency-injection registrations for application handlers.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class HandlerRegistrationGenerator : IIncrementalGenerator
{
    private const string HandlerMetadataName = "Kijk.Application.IHandler";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = GeneratorUtilities.CreateImplementationsProvider(context, HandlerMetadataName);
        context.RegisterSourceOutput(
            handlers.Collect().Combine(context.CompilationProvider),
            static (sourceContext, input) =>
            {
                if (GeneratorUtilities.IsDefiningCompilation(input.Right, HandlerMetadataName))
                {
                    Execute(sourceContext, input.Left);
                }
            });
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> candidates)
    {
        var handlers = GeneratorUtilities.GetDistinctOrderedSymbols(candidates)
            .Where(handler => !GeneratorUtilities.ReportGenericType(context, handler))
            .ToArray();

        context.AddSource("GeneratedHandlerRegistrations.g.cs", SourceText.From(Render(handlers), Encoding.UTF8));
    }

    private static string Render(IReadOnlyCollection<INamedTypeSymbol> handlers)
    {
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            namespace Kijk.Application;

            internal static class GeneratedHandlerRegistrations
            {
                internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHandlers(
                    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
            """);

        foreach (var handler in handlers)
        {
            RenderRegistration(source, handler);
        }

        return source.AppendLine("        return services;")
            .AppendLine("    }")
            .AppendLine("}")
            .ToString();
    }

    private static void RenderRegistration(StringBuilder source, INamedTypeSymbol handler)
    {
        var handlerMarker = handler.AllInterfaces.First(static @interface => @interface.ToDisplayString() == HandlerMetadataName);
        var serviceInterfaces = handler.AllInterfaces
            .Where(@interface => !SymbolEqualityComparer.Default.Equals(@interface, handlerMarker))
            .OrderBy(static @interface => @interface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
            .ToArray();
        var handlerName = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (serviceInterfaces.Length == 0)
        {
            source.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<")
                .Append(handlerName)
                .AppendLine(">(services);");
            return;
        }

        foreach (var serviceInterface in serviceInterfaces)
        {
            source.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<")
                .Append(serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Append(", ")
                .Append(handlerName)
                .AppendLine(">(services);");
        }
    }
}