using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Kijk.Api.SourceGenerators;

/// <summary>
/// Generates compile-time dependency-injection registrations for application modules.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ModuleRegistrationGenerator : IIncrementalGenerator
{
    private const string ModuleMetadataName = "Kijk.Application.IModule";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var modules = GeneratorUtilities.CreateImplementationsProvider(context, ModuleMetadataName);
        context.RegisterSourceOutput(
            modules.Collect().Combine(context.CompilationProvider),
            static (sourceContext, input) =>
            {
                if (GeneratorUtilities.IsDefiningCompilation(input.Right, ModuleMetadataName))
                {
                    Execute(sourceContext, input.Left);
                }
            });
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> candidates)
    {
        var modules = GeneratorUtilities.GetDistinctOrderedSymbols(candidates);
        var validModules = new List<INamedTypeSymbol>(modules.Length);

        foreach (var module in modules)
        {
            if (GeneratorUtilities.ReportGenericType(context, module))
            {
                continue;
            }

            if (!HasPublicParameterlessConstructor(module))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    GeneratorDiagnostics.InvalidModuleConstructor,
                    module.Locations.FirstOrDefault(),
                    module.Name));
                continue;
            }

            validModules.Add(module);
        }

        context.AddSource("GeneratedModuleRegistrations.g.cs", SourceText.From(Render(validModules), Encoding.UTF8));
    }

    private static bool HasPublicParameterlessConstructor(INamedTypeSymbol module) =>
        module.InstanceConstructors.Any(static constructor =>
            constructor.Parameters.IsEmpty && constructor.DeclaredAccessibility == Accessibility.Public);

    private static string Render(IReadOnlyCollection<INamedTypeSymbol> modules)
    {
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            namespace Kijk.Application;

            internal static class GeneratedModuleRegistrations
            {
                internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddModules(
                    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
            """);

        foreach (var module in modules)
        {
            source.Append("        ((global::Kijk.Application.IModule)new ")
                .Append(module.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .AppendLine("()).RegisterServices(services);");
        }

        return source.AppendLine("        return services;")
            .AppendLine("    }")
            .AppendLine("}")
            .ToString();
    }
}