# fly.toml app configuration file generated for kijk-api on 2024-04-01T18:47:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kijk-api'
primary_region = 'ams'

[build]
  dockerfile = 'Kijk.Api/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
