name: Api CI/CD 🚀

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["apps/api/**"]
  pull_request:
    branches: ["main", "develop"]
    paths: ["apps/api/**"]

env:
  DOTNET_VERSION: "8.0.x"

defaults:
  run:
    working-directory: ./apps/api

jobs:
  basic:
    name: "🛠️ Build, Lint/Format & Test"
    runs-on: ubuntu-latest

    steps:
      - name: 🏖️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 Install dependencies
        run: dotnet restore "Kijk.Api/Kijk.Api.csproj"

      - name: 🧱 Build
        run: dotnet build "Kijk.Api/Kijk.Api.csproj" -c Release --no-restore

      - name: 🧹 Format
        run: dotnet format --verify-no-changes --verbosity detailed --exclude 'Kijk.Api/Persistence/Migrations/'

      - name: 🧪 Test
        run: dotnet test "Kijk.Api/Kijk.Api.csproj" --configuration Release --no-build

      - name: 🔍 Audit
        run: |
          dotnet list package --vulnerable --include-transitive --format=json > list.json
          if jq -cre '.projects | .. | .severity? // empty | select(test("Critical"))' list.json; then
            echo 'Vulnerabilities found! Exiting...'
            jq . list.json
            exit 1
          else
            echo 'No vulnerabilities found!'
          fi
        continue-on-error: true
