name: Client 💻

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/client.yml"
      - "apps/client/**"
      - "package.json"
      - "packages/config/**"
      - "packages/core/**"
      - "packages/ui/**"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
  pull_request:
    branches: ["main", "develop"]
    paths:
      - ".github/workflows/client.yml"
      - "apps/client/**"
      - "package.json"
      - "packages/config/**"
      - "packages/core/**"
      - "packages/ui/**"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"

jobs:
  basic:
    name: "🛠️ Build, Lint/Format"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: "🏖️ Checkout Repository"
        uses: actions/checkout@v6

      - name: "🔧 Install pnpm"
        uses: pnpm/action-setup@v6
        id: pnpm-install

      - name: "🔧 Use Node.js"
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: "📦 Install dependencies"
        run: pnpm ci
      # Enable at later time
      # - name: Run the tests and generate coverage report
      #   run: npm test -- --coverage

      - name: "🧱 Build"
        run: pnpm build:client

      - name: "🧪 Typecheck"
        run: pnpm --filter kijk-client --filter @kijk/config --filter @kijk/core --filter @kijk/ui typecheck

      - name: "🧹 Format"
        run: pnpm --filter kijk-client --filter @kijk/config --filter @kijk/core --filter @kijk/ui fmt

      - name: "🔍 Lint"
        run: pnpm --filter kijk-client --filter @kijk/config --filter @kijk/core --filter @kijk/ui lint

      - name: "🔍 Audit"
        run: pnpm audit
        continue-on-error: true
