name: Client 💻

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/client.yml"
      - "apps/client/**"
      - "package.json"
      - "packages/config/**"
      - "packages/core/**"
      - "packages/ui/**"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
  pull_request:
    branches: ["main", "develop"]
    paths:
      - ".github/workflows/client.yml"
      - "apps/client/**"
      - "package.json"
      - "packages/config/**"
      - "packages/core/**"
      - "packages/ui/**"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"

permissions:
  contents: read

jobs:
  basic:
    name: "🛠️ Build, Lint/Format"
    runs-on: ubuntu-latest

    steps:
      - name: "🏖️ Checkout Repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "🔧 Install pnpm"
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        id: pnpm-install

      - name: "🔧 Use Node.js"
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: "📦 Install dependencies"
        run: pnpm ci
      # Enable at later time
      # - name: Run the tests and generate coverage report
      #   run: npm test -- --coverage

      - name: "🧱 Build"
        run: pnpm build:client

      - name: "🧪 Typecheck"
        run: pnpm --filter kijk-client --filter @kijk/config --filter @kijk/core --filter @kijk/ui typecheck

      - name: "🧹 Format"
        run: pnpm --filter kijk-client --filter @kijk/config --filter @kijk/core --filter @kijk/ui fmt

      - name: "🔍 Lint"
        run: pnpm --filter kijk-client --filter @kijk/config --filter @kijk/core --filter @kijk/ui lint

      - name: "🔍 Audit"
        run: pnpm audit
        continue-on-error: true
