# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Next.js CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ['apps/nextjs-web/**', '.github/workflows/nextjs.yml']

  pull_request:
    branches: ["main", "develop"]
    paths: ['apps/nextjs-web/**', '.github/workflows/nextjs.yml']

jobs:
  web-ci:
    name: "Build, lint, and test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: ./apps/nextjs-web

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # Enable at later time
      # - name: Run the tests and generate coverage report
      #   run: npm test -- --coverage
      # - name: Build
      #   run: pnpm build
      - name: Lint
        run: pnpm lint

      - name: Style
        run: pnpm format:check

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
