name: Next.js CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ['apps/nextjs-web/**', '.github/workflows/nextjs.yml']

  pull_request:
    branches: ["main", "develop"]
    paths: ['apps/nextjs-web/**', '.github/workflows/nextjs.yml']

jobs:
  Install:
    name: "Build, lint, and test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: ./apps/nextjs-web

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # Enable at later time
      # - name: Run the tests and generate coverage report
      #   run: npm test -- --coverage
      # - name: Build
      #   run: pnpm build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: next-root-artifact
          path: .

  Lint_format:
    name: Run eslint and prettier
    runs-on: ubuntu-latest
    needs: [Install]
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      # Download previously shared root folder
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: next-root-artifact

      - name: Format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
